// Maharashtra Manganese AI - High-fidelity Mock Dataset
// Realistic MOIL Nagpur, Bhandara, and Balaghat manganese mining data

export const MOCK_MINES = [
  {
    mine_id: "MOIL_DB_01",
    mine_name: "Dongri Buzurg Mine",
    district: "Bhandara",
    state: "Maharashtra",
    type: "Opencast",
    lat: 21.5542,
    lon: 79.6975,
    primary_ore: "Pyrolusite & Psilomelane (Dioxide / Battery Grade)",
    typical_grade_mn: 48.5,
    p_content_pct: 0.08,
    sio2_pct: 6.2,
    fe_pct: 4.5,
    status: "Active Operational",
    annual_capacity_mt: 450000,
    current_production_mtd: 38200,
    expected_production_mtd: 41000,
    monthly_target_mtd: 40000,
    reserve_estimate_mt: 14.8, // Million Tonnes
    shortfall_risk_pct: 22,
    equipment_fleet: {
      excavators: { total: 8, active: 7, maintenance: 1 },
      dumpers: { total: 24, active: 21, maintenance: 3 },
      crushers: { total: 3, active: 3, maintenance: 0 },
      drills: { total: 6, active: 5, maintenance: 1 },
      oee_pct: 84.6
    },
    active_risks: [
      { id: "r1", type: "Equipment", severity: "Medium", desc: "Dumper D-14 transmission maintenance scheduled in 48h." },
      { id: "r2", type: "Weather", severity: "Low", desc: "Slight pit ramp slip alert during evening pre-monsoon shower." }
    ],
    predicted_production_next_month: 42500,
    recommended_action: "Increase overburden bench stripping at Pit North to unlock 18,000 MT of 49% Mn dioxide grade ore."
  },
  {
    mine_id: "MOIL_BG_02",
    mine_name: "Balaghat (Bharweli) Mine",
    district: "Balaghat",
    state: "Madhya Pradesh (MOIL Belt)",
    type: "Underground (Asia's Deepest Mn Mine)",
    lat: 21.8672,
    lon: 80.2015,
    primary_ore: "Braunite & Bixbyite (Metallurgical High Grade)",
    typical_grade_mn: 46.2,
    p_content_pct: 0.12,
    sio2_pct: 8.1,
    fe_pct: 5.8,
    status: "Active Operational",
    annual_capacity_mt: 600000,
    current_production_mtd: 46500,
    expected_production_mtd: 52000,
    monthly_target_mtd: 50000,
    reserve_estimate_mt: 22.4,
    shortfall_risk_pct: 68,
    equipment_fleet: {
      excavators: { total: 4, active: 3, maintenance: 1 },
      dumpers: { total: 18, active: 14, maintenance: 4 },
      crushers: { total: 2, active: 2, maintenance: 0 },
      drills: { total: 10, active: 8, maintenance: 2 },
      oee_pct: 73.8
    },
    active_risks: [
      { id: "r3", type: "Logistics", severity: "High", desc: "Winder hoist cage 2 scheduled rope inspection causing 6-hour hoisting bottleneck." },
      { id: "r4", type: "Blasting", severity: "Critical", desc: "Ventilation clearance delay at -450m RL level stope." }
    ],
    predicted_production_next_month: 48900,
    recommended_action: "Prioritize level 18 stope backfilling and re-route haulage locos to auxiliary shaft to offset hoisting deficit."
  },
  {
    mine_id: "MOIL_MN_03",
    mine_name: "Mansar Mine",
    district: "Nagpur",
    state: "Maharashtra",
    type: "Opencast & Underground",
    lat: 21.398,
    lon: 79.2885,
    primary_ore: "Braunite & Cryptomelane",
    typical_grade_mn: 41.0,
    p_content_pct: 0.15,
    sio2_pct: 11.5,
    fe_pct: 7.2,
    status: "Active Operational",
    annual_capacity_mt: 220000,
    current_production_mtd: 17400,
    expected_production_mtd: 18500,
    monthly_target_mtd: 18000,
    reserve_estimate_mt: 8.1,
    shortfall_risk_pct: 35,
    equipment_fleet: {
      excavators: { total: 5, active: 4, maintenance: 1 },
      dumpers: { total: 14, active: 12, maintenance: 2 },
      crushers: { total: 2, active: 1, maintenance: 1 },
      drills: { total: 4, active: 4, maintenance: 0 },
      oee_pct: 79.2
    },
    active_risks: [
      { id: "r5", type: "Equipment", severity: "High", desc: "Secondary vibrating screen mesh tear in beneficiation unit." }
    ],
    predicted_production_next_month: 19100,
    recommended_action: "Deploy mobile crushing unit to bypass stationary plant during vibrating screen overhaul."
  },
  {
    mine_id: "MOIL_GG_04",
    mine_name: "Gumgaon Mine",
    district: "Nagpur",
    state: "Maharashtra",
    type: "Underground",
    lat: 21.4022,
    lon: 78.9864,
    primary_ore: "Braunite & Gondite Banded Ore",
    typical_grade_mn: 39.5,
    p_content_pct: 0.18,
    sio2_pct: 14.0,
    fe_pct: 8.0,
    status: "Active Operational",
    annual_capacity_mt: 180000,
    current_production_mtd: 14100,
    expected_production_mtd: 15500,
    monthly_target_mtd: 15000,
    reserve_estimate_mt: 5.6,
    shortfall_risk_pct: 48,
    equipment_fleet: {
      excavators: { total: 3, active: 2, maintenance: 1 },
      dumpers: { total: 10, active: 8, maintenance: 2 },
      crushers: { total: 1, active: 1, maintenance: 0 },
      drills: { total: 5, active: 4, maintenance: 1 },
      oee_pct: 76.5
    },
    active_risks: [
      { id: "r6", type: "Grade Dilution", severity: "Medium", desc: "Hanging wall schist dilution on East Winze dropping run-of-mine grade to 36.8%." }
    ],
    predicted_production_next_month: 14900,
    recommended_action: "Adjust blast hole burden from 1.8m to 1.4m to reduce hanging wall overbreak and ore dilution."
  },
  {
    mine_id: "MOIL_KD_05",
    mine_name: "Kandri Mine",
    district: "Nagpur",
    state: "Maharashtra",
    type: "Opencast & Underground",
    lat: 21.4173,
    lon: 79.2714,
    primary_ore: "High Grade Braunite Ore",
    typical_grade_mn: 44.0,
    p_content_pct: 0.14,
    sio2_pct: 9.4,
    fe_pct: 6.5,
    status: "Active Operational",
    annual_capacity_mt: 160000,
    current_production_mtd: 13900,
    expected_production_mtd: 14000,
    monthly_target_mtd: 13500,
    reserve_estimate_mt: 6.2,
    shortfall_risk_pct: 15,
    equipment_fleet: {
      excavators: { total: 4, active: 4, maintenance: 0 },
      dumpers: { total: 12, active: 11, maintenance: 1 },
      crushers: { total: 2, active: 2, maintenance: 0 },
      drills: { total: 4, active: 3, maintenance: 1 },
      oee_pct: 88.0
    },
    active_risks: [
      { id: "r7", type: "Blasting", severity: "Low", desc: "Vibration monitoring sensor recalibration in progress." }
    ],
    predicted_production_next_month: 14500,
    recommended_action: "Maintain steady opencast feed and accelerate pilot drift toward West limb extension."
  },
  {
    mine_id: "MOIL_UK_06",
    mine_name: "Ukwa Mine",
    district: "Balaghat",
    state: "Madhya Pradesh (MOIL Belt)",
    type: "Underground",
    lat: 21.968,
    lon: 80.467,
    primary_ore: "Fine Grained Braunite & Hollandite",
    typical_grade_mn: 42.5,
    p_content_pct: 0.11,
    sio2_pct: 10.2,
    fe_pct: 5.9,
    status: "Active Operational",
    annual_capacity_mt: 200000,
    current_production_mtd: 16200,
    expected_production_mtd: 17200,
    monthly_target_mtd: 16800,
    reserve_estimate_mt: 9.3,
    shortfall_risk_pct: 32,
    equipment_fleet: {
      excavators: { total: 3, active: 3, maintenance: 0 },
      dumpers: { total: 11, active: 9, maintenance: 2 },
      crushers: { total: 2, active: 2, maintenance: 0 },
      drills: { total: 6, active: 5, maintenance: 1 },
      oee_pct: 81.3
    },
    active_risks: [
      { id: "r8", type: "Transportation", severity: "Medium", desc: "Haulage road wet patches slowing dumper cycle time by 14%." }
    ],
    predicted_production_next_month: 17400,
    recommended_action: "Apply gravel grading on Eastern arterial haul route and schedule night shift continuous haulage."
  },
  {
    mine_id: "MOIL_TR_07",
    mine_name: "Tirodi Mine",
    district: "Balaghat",
    state: "Madhya Pradesh (MOIL Belt)",
    type: "Opencast",
    lat: 21.6841,
    lon: 79.7112,
    primary_ore: "Braunite & Quartz Gondite Ore",
    typical_grade_mn: 38.0,
    p_content_pct: 0.2,
    sio2_pct: 15.5,
    fe_pct: 8.5,
    status: "Active Operational",
    annual_capacity_mt: 250000,
    current_production_mtd: 19800,
    expected_production_mtd: 22000,
    monthly_target_mtd: 21000,
    reserve_estimate_mt: 7.8,
    shortfall_risk_pct: 42,
    equipment_fleet: {
      excavators: { total: 5, active: 4, maintenance: 1 },
      dumpers: { total: 16, active: 13, maintenance: 3 },
      crushers: { total: 2, active: 2, maintenance: 0 },
      drills: { total: 5, active: 4, maintenance: 1 },
      oee_pct: 77.4
    },
    active_risks: [
      { id: "r9", type: "Railway Logistics", severity: "High", desc: "SECR Railway rake placement delayed by 36 hours at Tirodi siding." }
    ],
    predicted_production_next_month: 21300,
    recommended_action: "Stockpile ROM ore at siding bin 3 and coordinate with SECR division for priority rake allocation."
  },
  {
    mine_id: "MOIL_CK_08",
    mine_name: "Chikla Mine",
    district: "Bhandara",
    state: "Maharashtra",
    type: "Underground",
    lat: 21.5501,
    lon: 79.7503,
    primary_ore: "Braunite Ore Body",
    typical_grade_mn: 43.0,
    p_content_pct: 0.16,
    sio2_pct: 10.0,
    fe_pct: 6.8,
    status: "Active Operational",
    annual_capacity_mt: 300000,
    current_production_mtd: 23600,
    expected_production_mtd: 25500,
    monthly_target_mtd: 25000,
    reserve_estimate_mt: 11.2,
    shortfall_risk_pct: 38,
    equipment_fleet: {
      excavators: { total: 4, active: 3, maintenance: 1 },
      dumpers: { total: 15, active: 13, maintenance: 2 },
      crushers: { total: 2, active: 2, maintenance: 0 },
      drills: { total: 7, active: 6, maintenance: 1 },
      oee_pct: 80.5
    },
    active_risks: [
      { id: "r10", type: "Equipment", severity: "Medium", desc: "Sub-surface ventilation fan 2 motor bearing vibration warning." }
    ],
    predicted_production_next_month: 25100,
    recommended_action: "Switch to auxiliary ventilation standby unit and perform preventive bearing replacement during low-traffic window."
  }
];

export const MOCK_EXPLORATION_ZONES = [
  {
    rank: 1,
    grid_id: "MN_EXP_7928_2156",
    zone_name: "Dongri-Chikla North Fold",
    district: "Bhandara",
    state: "Maharashtra",
    lat: 21.562,
    lon: 79.715,
    mn_probability_pct: 94.2,
    predicted_grade_mn_pct: 48.9,
    grade_category: "Ferro-Grade High",
    unfc_stage: "G2 General",
    environmental_status: "CLEAR (Outside ESZ)",
    iron_oxide_index: 2.84,
    gossan_index: 3.42,
    lst_celsius: 38.6,
    elevation_m: 342,
    pench_esz_dist_km: 18.4,
    predicted_reserve_mt: 4.85,
    priority: "Critical",
    priority_code: "critical",
    geological_indicator: "Quartz-braunite synformal syncline with strong surface iron-manganese capping",
    ai_recommendation: "Execute 12 close-spaced G1 core drillholes (150m depth) to confirm sub-surface continuity."
  },
  {
    rank: 2,
    grid_id: "MN_EXP_7931_2142",
    zone_name: "Mansar-Kandri Deep Extension",
    district: "Nagpur",
    state: "Maharashtra",
    lat: 21.411,
    lon: 79.294,
    mn_probability_pct: 91.5,
    predicted_grade_mn_pct: 46.8,
    grade_category: "Ferro-Grade High",
    unfc_stage: "G2 General",
    environmental_status: "CLEAR (Outside ESZ)",
    iron_oxide_index: 2.71,
    gossan_index: 3.18,
    lst_celsius: 39.1,
    elevation_m: 310,
    pench_esz_dist_km: 14.2,
    predicted_reserve_mt: 3.90,
    priority: "Critical",
    priority_code: "critical",
    geological_indicator: "Sausar Group Mansar formation gondite band down-dip extension",
    ai_recommendation: "Coordinate 3D Seismic and IP Survey to pinpoint ore body depth between Mansar and Kandri."
  },
  {
    rank: 3,
    grid_id: "MN_EXP_8022_2189",
    zone_name: "Bharweli-Ganga Suture",
    district: "Balaghat",
    state: "Madhya Pradesh",
    lat: 21.884,
    lon: 80.218,
    mn_probability_pct: 88.7,
    predicted_grade_mn_pct: 45.4,
    grade_category: "Ferro-Grade High",
    unfc_stage: "G3 Prospecting",
    environmental_status: "REGULATED (Buffer Zone)",
    iron_oxide_index: 2.55,
    gossan_index: 2.95,
    lst_celsius: 37.4,
    elevation_m: 388,
    pench_esz_dist_km: 26.5,
    predicted_reserve_mt: 5.20,
    priority: "Critical",
    priority_code: "critical",
    geological_indicator: "High-grade braunite shear zone with magnetic anomaly alignment",
    ai_recommendation: "Apply for Stage-1 Forest Exploration clearance; deploy non-invasive magnetic gradient survey."
  },
  {
    rank: 4,
    grid_id: "MN_EXP_7974_2169",
    zone_name: "Tirodi West Limb",
    district: "Balaghat",
    state: "Madhya Pradesh",
    lat: 21.691,
    lon: 79.702,
    mn_probability_pct: 83.4,
    predicted_grade_mn_pct: 42.1,
    grade_category: "Medium Metallurgical",
    unfc_stage: "G3 Prospecting",
    environmental_status: "CLEAR (Outside ESZ)",
    iron_oxide_index: 2.38,
    gossan_index: 2.64,
    lst_celsius: 38.0,
    elevation_m: 355,
    pench_esz_dist_km: 21.0,
    predicted_reserve_mt: 2.75,
    priority: "High",
    priority_code: "high",
    geological_indicator: "Quartzite-gondite interbedding with visible pyrolusite float ore",
    ai_recommendation: "Trenching and 5 exploratory rotary drillholes to establish seam thickness."
  },
  {
    rank: 5,
    grid_id: "MN_EXP_7899_2141",
    zone_name: "Gumgaon South Axis",
    district: "Nagpur",
    state: "Maharashtra",
    lat: 21.391,
    lon: 78.974,
    mn_probability_pct: 79.8,
    predicted_grade_mn_pct: 40.5,
    grade_category: "Medium Metallurgical",
    unfc_stage: "G3 Prospecting",
    environmental_status: "CLEAR (Outside ESZ)",
    iron_oxide_index: 2.22,
    gossan_index: 2.41,
    lst_celsius: 39.8,
    elevation_m: 298,
    pench_esz_dist_km: 16.8,
    predicted_reserve_mt: 2.10,
    priority: "High",
    priority_code: "high",
    geological_indicator: "Mica schist contact zone showing moderate spectral thermal anomaly",
    ai_recommendation: "Carry out geochemical soil sampling grid (50m x 50m)."
  },
  {
    rank: 6,
    grid_id: "MN_EXP_8048_2198",
    zone_name: "Ukwa East Extension",
    district: "Balaghat",
    state: "Madhya Pradesh",
    lat: 21.979,
    lon: 80.485,
    mn_probability_pct: 76.2,
    predicted_grade_mn_pct: 41.8,
    grade_category: "Medium Metallurgical",
    unfc_stage: "G4 Reconnaissance",
    environmental_status: "REGULATED (Buffer Zone)",
    iron_oxide_index: 2.15,
    gossan_index: 2.30,
    lst_celsius: 36.9,
    elevation_m: 415,
    pench_esz_dist_km: 32.1,
    predicted_reserve_mt: 3.40,
    priority: "High",
    priority_code: "high",
    geological_indicator: "Phyllitic host rock with manganese oxide encrustations",
    ai_recommendation: "Detailed drone LIDAR topographic survey and airborne geophysical anomaly correlation."
  },
  {
    rank: 7,
    grid_id: "MN_EXP_7912_2136",
    zone_name: "Ramtek-Parseoni Corridor",
    district: "Nagpur",
    state: "Maharashtra",
    lat: 21.365,
    lon: 79.182,
    mn_probability_pct: 68.4,
    predicted_grade_mn_pct: 38.2,
    grade_category: "Silico-Manganese Grade",
    unfc_stage: "G4 Reconnaissance",
    environmental_status: "CLEAR (Outside ESZ)",
    iron_oxide_index: 1.95,
    gossan_index: 2.05,
    lst_celsius: 40.2,
    elevation_m: 285,
    pench_esz_dist_km: 11.5,
    predicted_reserve_mt: 1.65,
    priority: "Medium",
    priority_code: "medium",
    geological_indicator: "Quartzite ridge capping with disseminated manganese nodular occurrences",
    ai_recommendation: "Pitting and regional geological reconnaissance mapping."
  },
  {
    rank: 8,
    grid_id: "MN_EXP_7988_2151",
    zone_name: "Tumsar-Bawanthadi Basin",
    district: "Bhandara",
    state: "Maharashtra",
    lat: 21.512,
    lon: 79.821,
    mn_probability_pct: 64.9,
    predicted_grade_mn_pct: 37.5,
    grade_category: "Silico-Manganese Grade",
    unfc_stage: "G4 Reconnaissance",
    environmental_status: "CLEAR (Outside ESZ)",
    iron_oxide_index: 1.88,
    gossan_index: 1.92,
    lst_celsius: 38.9,
    elevation_m: 305,
    pench_esz_dist_km: 24.0,
    predicted_reserve_mt: 1.40,
    priority: "Medium",
    priority_code: "medium",
    geological_indicator: "Alluvial covered gondite horizon detected via Landsat TIR thermal contrast",
    ai_recommendation: "Shallow auger drilling to penetrate overburden."
  },
  {
    rank: 9,
    grid_id: "MN_EXP_7945_2170",
    zone_name: "Pench River Escarpment Zone",
    district: "Nagpur",
    state: "Maharashtra",
    lat: 21.655,
    lon: 79.312,
    mn_probability_pct: 58.0,
    predicted_grade_mn_pct: 36.0,
    grade_category: "Low Grade Refractory",
    unfc_stage: "G4 Reconnaissance",
    environmental_status: "RESTRICTED (Pench ESZ Core)",
    iron_oxide_index: 1.72,
    gossan_index: 1.78,
    lst_celsius: 35.8,
    elevation_m: 360,
    pench_esz_dist_km: 3.2,
    predicted_reserve_mt: 1.10,
    priority: "Medium",
    priority_code: "medium",
    geological_indicator: "Banded manganese iron formation inside national park ecological buffer",
    ai_recommendation: "Hold physical operations; retain on remote sensing satellite monitoring only."
  }
];

export const MOCK_PRODUCTION_FORECAST = [
  { month: "Jan", actual: 168000, expected: 170000, demand: 175000, shortfall: 7000, prob_shortfall: 28 },
  { month: "Feb", actual: 172500, expected: 174000, demand: 178000, shortfall: 5500, prob_shortfall: 22 },
  { month: "Mar", actual: 181000, expected: 180000, demand: 185000, shortfall: 4000, prob_shortfall: 18 },
  { month: "Apr", actual: 179200, expected: 182000, demand: 190000, shortfall: 10800, prob_shortfall: 45 },
  { month: "May", actual: 174600, expected: 185000, demand: 195000, shortfall: 20400, prob_shortfall: 62 },
  { month: "Jun (Current)", actual: 176400, expected: 188700, demand: 202000, shortfall: 25600, prob_shortfall: 74 },
  { month: "Jul", actual: null, expected: 184000, demand: 205000, shortfall: 21000, prob_shortfall: 68, forecast_low: 172000, forecast_high: 192000 },
  { month: "Aug", actual: null, expected: 178000, demand: 208000, shortfall: 30000, prob_shortfall: 82, forecast_low: 165000, forecast_high: 186000 },
  { month: "Sep", actual: null, expected: 192000, demand: 210000, shortfall: 18000, prob_shortfall: 56, forecast_low: 180000, forecast_high: 201000 },
  { month: "Oct", actual: null, expected: 208000, demand: 215000, shortfall: 7000, prob_shortfall: 31, forecast_low: 198000, forecast_high: 217000 },
  { month: "Nov", actual: null, expected: 215000, demand: 218000, shortfall: 3000, prob_shortfall: 19, forecast_low: 205000, forecast_high: 224000 },
  { month: "Dec", actual: null, expected: 222000, demand: 220000, shortfall: 0, prob_shortfall: 11, forecast_low: 212000, forecast_high: 231000 }
];

export const MOCK_RISKS = [
  {
    id: "RSK-01",
    category: "Equipment Downtime",
    icon: "Wrench",
    title: "Primary Shovel & Hoist Cage Downtime",
    mine: "Balaghat & Mansar",
    severity: "Critical",
    severity_level: 4,
    impact: "-4,200 MT/week lost extraction",
    root_cause: "Hydraulic pump assembly delay at Balaghat Central Winder; Komatsu excavator track-chain wear at Mansar Pit 2.",
    status: "Mitigation in Progress",
    ai_mitigation: "Re-assign standby Komatsu PC400 from Chikla siding and throttle South Winze hoisting rate to 90% duty cycle.",
    updated_at: "18 mins ago"
  },
  {
    id: "RSK-02",
    category: "Weather & Monsoon",
    icon: "CloudRain",
    title: "Pre-Monsoon Drainage Pit Water Ingress",
    mine: "Dongri Buzurg & Tirodi",
    severity: "High",
    severity_level: 3,
    impact: "Haulage speed down 32%, sump level +1.8m",
    root_cause: "High-intensity rainfall localized over Vidarbha-Bhandara ridge causing runoff into Bench 4.",
    status: "Active Alert",
    ai_mitigation: "Activate 3 high-capacity submersible dewatering pumps (150 HP) and route dumpers via upper ridge bypass road.",
    updated_at: "45 mins ago"
  },
  {
    id: "RSK-03",
    category: "Blasting Delays",
    icon: "Zap",
    title: "Seismic & Residential Proximity Restriction",
    mine: "Kandri North Pit",
    severity: "Moderate",
    severity_level: 2,
    impact: "24h cycle postponement (-1,800 MT ROM)",
    root_cause: "Ground vibration limits near residential perimeter exceeding 5.0 mm/s DGMS threshold.",
    status: "Optimized Pattern Ready",
    ai_mitigation: "Switch to Electronic Delay Detonators (EDDs) with 17ms interval stagger and reduce charge per delay by 22%.",
    updated_at: "2 hours ago"
  },
  {
    id: "RSK-04",
    category: "Transportation & Logistics",
    icon: "Truck",
    title: "SECR Railway Rake Deficit at Tirodi Siding",
    mine: "Tirodi & Ukwa",
    severity: "High",
    severity_level: 3,
    impact: "Stockpile saturation at 42,000 MT, loading demurrage risk",
    root_cause: "Freight rake turnaround delayed by 38 hours on Nagpur-Bilaspur railway trunk corridor.",
    status: "Escalated to Logistics Cell",
    ai_mitigation: "Divert 30% of high-grade sinter feed to Nagpur steel plant via emergency road multi-axle tippers.",
    updated_at: "3 hours ago"
  },
  {
    id: "RSK-05",
    category: "Ore Grade Dilution",
    icon: "Layers",
    title: "Silica & Phosphorus Influx in ROM Feed",
    mine: "Gumgaon Underground",
    severity: "Moderate",
    severity_level: 2,
    impact: "Mn recovery drops from 41% to 37.1%",
    root_cause: "Hanging wall schist contamination during retreat stoping in Level 4 block.",
    status: "Blending Plan Issued",
    ai_mitigation: "Blend Gumgaon low-grade feed (37% Mn) with Dongri Buzurg high-grade dioxide ore (48.5% Mn) in ratio 1:2.4.",
    updated_at: "5 hours ago"
  }
];

export const MOCK_AI_RECOMMENDATIONS = [
  {
    id: "REC-AI-101",
    category: "Mine Schedule & Production",
    title: "Re-balance Production: Dongri Buzurg + Balaghat",
    badge: "High Impact",
    confidence_score: 96,
    impact: "+14,500 MT Output | -62% Shortfall Risk",
    summary: "Increase Dongri Buzurg opencast strip mining by 18% to offset Balaghat underground winder hoist maintenance downtime over the next 14 days.",
    affected_assets: ["Dongri Buzurg Mine", "Balaghat Mine", "Central Beneficiation Plant"],
    action_type: "Schedule Adjustment",
    details: [
      "Dongri Buzurg opencast has 48.5% Mn ore readily accessible at Bench 3.",
      "Balaghat shaft cage maintenance reduces daily hoisting capacity by 650 MT/day for 10 days.",
      "Net production will equalize with zero penalty on grade composition."
    ],
    status: "Pending Approval"
  },
  {
    id: "REC-AI-102",
    category: "Fleet Re-deployment",
    title: "Re-deploy 4 Heavy Haul Dumpers to Mansar Pit",
    badge: "Equipment Optimization",
    confidence_score: 92,
    impact: "+3,200 MT/week ROM Haulage | +11% OEE",
    summary: "Temporarily relocate 4 idle CAT 773E dumpers from Tirodi stockyard to Mansar Mine West Pit to accelerate ore transfer to the secondary crusher.",
    affected_assets: ["Mansar Mine", "Tirodi Mine", "Fleet Management Cell"],
    action_type: "Fleet Dispatch",
    details: [
      "Tirodi haulage requirements temporarily lowered due to siding rake congestion.",
      "Mansar secondary crusher operating at only 68% capacity due to haul truck shortage.",
      "Estimated transit time: 2.5 hours via NH-747."
    ],
    status: "Pending Approval"
  },
  {
    id: "REC-AI-103",
    category: "Blasting Optimization",
    title: "Implement Electronic Delay Detonator Stagger Pattern",
    badge: "Safety & Efficiency",
    confidence_score: 94,
    impact: "-40% Ground Vibration | +18% Rock Fragmentation",
    summary: "Adopt AI-calculated 17ms inter-hole delay and 42ms inter-row delay with 80mm hole diameter at Kandri North Pit to eliminate DGMS vibration alerts.",
    affected_assets: ["Kandri Mine", "Drilling & Blasting Division"],
    action_type: "Blast Pattern Adjustment",
    details: [
      "Reduces flyrock risk to zero within 300m perimeter.",
      "Optimizes rock fragmentation (P80 < 250mm), reducing secondary breaking costs by 22%."
    ],
    status: "Approved"
  },
  {
    id: "REC-AI-104",
    category: "Exploration Prioritization",
    title: "Fast-track 12 G1 Boreholes at Dongri-Chikla Fold",
    badge: "Strategic Exploration",
    confidence_score: 98,
    impact: "+4.85 MT Confirmed Reserve Potential (48.9% Mn)",
    summary: "Allocate 2 diamond core drilling rigs to Zone MN_EXP_7928_2156 immediately. Satellite spectral indices show peak iron oxide and gossan correlation.",
    affected_assets: ["Geological Exploration Wing", "Bhandara District"],
    action_type: "Exploration Dispatch",
    details: [
      "Thermal LST anomaly of 38.6°C matches high-density pyrolusite sub-outcrop signatures.",
      "Outside Pench ESZ with 100% environmental clearance.",
      "Expected timeline to UNFC G1 conversion: 90 days."
    ],
    status: "In Progress"
  },
  {
    id: "REC-AI-105",
    category: "Grade Blending & Processing",
    title: "Automated Ore Grade Blending Matrix at Siding",
    badge: "Quality Assurance",
    confidence_score: 91,
    impact: "Guarantees 44.5% Ferro-Grade Delivery to Bhilai & Rourkela",
    summary: "Blend Gumgaon 39.5% Mn ore with Mansar 44% and Dongri 48.5% dioxide ore in 2:3:4 ratio at Ramtek central siding.",
    affected_assets: ["Ramtek Siding", "Gumgaon Mine", "Mansar Mine"],
    action_type: "Grade Optimization",
    details: [
      "Prevents buyer price penalty on low phosphorus tolerance (<0.12% P).",
      "Maximizes total revenue realization per tonne dispatched."
    ],
    status: "Pending Approval"
  }
];

export const MOCK_ANALYTICS = {
  grade_distribution: [
    { range: "< 35% Mn (Low)", tonnes_k: 45, count: 8, color: "#64748b" },
    { range: "35% - 40% Mn (Medium)", tonnes_k: 120, count: 22, color: "#f59e0b" },
    { range: "40% - 44% Mn (Standard Ferro)", tonnes_k: 285, count: 48, color: "#3b82f6" },
    { range: "44% - 48% Mn (High Grade)", tonnes_k: 390, count: 64, color: "#10b981" },
    { range: "> 48% Mn (Battery / Dioxide)", tonnes_k: 160, count: 18, color: "#8b5cf6" }
  ],
  reserve_trends: [
    { year: "2020", proved_reserves_mt: 72.4, probable_reserves_mt: 38.1, annual_depletion_mt: 2.1 },
    { year: "2021", proved_reserves_mt: 74.8, probable_reserves_mt: 41.5, annual_depletion_mt: 2.2 },
    { year: "2022", proved_reserves_mt: 78.2, probable_reserves_mt: 46.0, annual_depletion_mt: 2.4 },
    { year: "2023", proved_reserves_mt: 82.5, probable_reserves_mt: 51.2, annual_depletion_mt: 2.6 },
    { year: "2024", proved_reserves_mt: 86.9, probable_reserves_mt: 58.7, annual_depletion_mt: 2.8 },
    { year: "2025 (AI Additions)", proved_reserves_mt: 94.2, probable_reserves_mt: 68.3, annual_depletion_mt: 3.1 }
  ],
  demand_vs_supply: [
    { category: "Steel Sinter Feed", demand_mt: 120000, supply_mt: 112000, gap_mt: -8000 },
    { category: "Ferro-Manganese (FeMn)", demand_mt: 65000, supply_mt: 58000, gap_mt: -7000 },
    { category: "Silico-Manganese (SiMn)", demand_mt: 40000, supply_mt: 42000, gap_mt: 2000 },
    { category: "EV Battery / EMD Grade", demand_mt: 18000, supply_mt: 12500, gap_mt: -5500 },
    { category: "Chemical & Fertilizer", demand_mt: 10000, supply_mt: 9800, gap_mt: -200 }
  ],
  equipment_oee: [
    { name: "Heavy Shovels / Excavators", availability: 89.2, performance: 84.1, quality: 97.5, oee: 73.1 },
    { name: "Haulage Dump Trucks", availability: 86.4, performance: 81.5, quality: 98.2, oee: 69.1 },
    { name: "Crushing & Screening", availability: 92.1, performance: 87.6, quality: 96.0, oee: 77.4 },
    { name: "Blast Hole Drilling", availability: 94.0, performance: 88.2, quality: 99.1, oee: 82.2 },
    { name: "Shaft Winder Hoists", availability: 84.5, performance: 79.0, quality: 98.8, oee: 65.9 }
  ],
  district_share: [
    { name: "Balaghat Belt", share: 44, production_mt: 98500, color: "#3b82f6" },
    { name: "Nagpur District", share: 32, production_mt: 71700, color: "#10b981" },
    { name: "Bhandara District", share: 24, production_mt: 53800, color: "#f59e0b" }
  ]
};

export const MOCK_SUMMARY_KPIS = {
  total_mines: 8,
  active_mines: 8,
  total_reserves_mt: 85.45,
  current_month_production_mt: 176400,
  expected_production_mt: 188700,
  monthly_demand_mt: 202000,
  predicted_shortfall_mt: 25600,
  shortfall_probability_pct: 74,
  avg_manganese_grade_pct: 43.8,
  high_probability_zones_count: 594,
  environmentally_clear_pct: 82.6,
  active_critical_risks: 2,
  total_ai_recommendations: 5
};
